pipeline {
    agent any

    stages {
        stage('Execute Unit Tests') {
            parallel {
                stage('Unit Test - Backend') {
                    agent {
                        docker {
                            image 'snakee/golang-junit:1.21'
                            reuseNode true
                            args '-u 0'
                        }
                    }
                    steps {
                        catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                            dir('bugtracker-backend') {
                                sh '''
                                go test -v ./... | go-junit-report > test-results.xml
                        '''
                            }
                        }
                    }
                    post {
                        always {
                            junit allowEmptyResults: true, testResults: 'bugtracker-backend/test-results.xml'
                            publishHTML target: [
                                reportDir: 'bugtracker-backend',
                                reportFiles: 'test-results.xml',
                                reportName: 'Backend Unit Test Report'
                            ]
                        }
                    }
                }

                stage('Unit Test - Frontend') {
                    agent {
                        docker {
                            image 'node:20'
                            reuseNode true
                            args '-u 0'
                        }
                    }
                    steps {
                        catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                            dir('bugtracker-frontend') {
                                sh '''
                            npm ci
                            npm audit fix --force
                            npm test
                        '''
                            }
                        }
                    }
                    post {
                        always {
                            junit allowEmptyResults: true, testResults: 'bugtracker-frontend/test-results.xml'
                            publishHTML target: [
                                reportDir: 'bugtracker-frontend',
                                reportFiles: 'test-results.xml',
                                reportName: 'Frontend Unit Test Report'
                            ]
                        }
                    }
                }
            }
        }

        stage('Launch Application') {
            agent {
                docker {
                    image 'docker:27.5.1'
                    reuseNode true
                    args '-v /var/run/docker.sock:/var/run/docker.sock -u 0'
                }
            }
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    sh '''
                    docker-compose up --build -d
                '''
                }
            }
        }

        stage('Execute API Tests') {
            agent {
                docker {
                    image 'mcr.microsoft.com/playwright:v1.44.0-focal'
                    reuseNode true
                    args '-u 0 --network=host'
                }
            }
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    dir('tests-api') {
                        sh '''
                            npx wait-port http://localhost:8080 --timeout=300000
                            npm ci
                            npx playwright test
                        '''
                    }
                }
            }
            post {
                always {
                    junit allowEmptyResults: true, testResults: 'tests-api/test-results/results.xml'
                    publishHTML target: [
                        reportDir: 'tests-api/test-results',
                        reportFiles: 'results.xml',
                        reportName: 'API Test Report'
                    ]
                }
            }
        }

        stage('Execute E2E Tests') {
            agent {
                docker {
                    image 'mcr.microsoft.com/playwright:v1.44.0-focal'
                    reuseNode true
                    args '-u 0 --network=host'
                }
            }
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    dir('tests-e2e') {
                        sh '''
                            npm ci
                            npx playwright test
                        '''
                    }
                }
            }
            post {
                always {
                    junit allowEmptyResults: true, testResults: 'tests-e2e/test-results/results.xml'
                    publishHTML target: [
                        reportDir: 'tests-e2e/test-results',
                        reportFiles: 'results.xml',
                        reportName: 'E2E Test Report'
                    ]
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
