pipeline {
    agent any

    stages {
        stage('Execute Unit Tests') {
            parallel {
            stage('Unit Test - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    dir('bugtracker-backend') {
                        sh '''
                            export GOCACHE="$PWD/.cache/go-build"
                            export GOMODCACHE="$PWD/.cache/go-mod"
                            mkdir -p "$GOCACHE"
                            mkdir -p "$GOMODCACHE"

                            echo "Go cache directory: $GOCACHE"
                            echo "Go module cache directory: $GOMODCACHE"
                            go env GOCACHE
                            go env GOMODCACHE

                            go test -v ./... | go-junit-report > test-results.xml
                        '''
                    }
                }
            }
            post {
                always {
                    junit 'bugtracker-backend/test-results.xml'
                }
            }
        }

        stage('Unit Test - Frontend') {
            agent {
                docker {
                    image 'node:20'
                    reuseNode true
                }
            }
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    dir('bugtracker-frontend') {
                        sh '''
                            npm ci
                            npm test
                        '''
                    }
                }
            }
            post {
                always {
                    junit 'bugtracker-frontend/test-results.xml'
                }
            }
        }
            }
        }

        stage('Launch Application') {
            agent {
                docker {
                    image 'docker:27.5.1'
                    reuseNode true
                    args '-v /var/run/docker.sock:/var/run/docker.sock'
                }
            }
            steps {
                sh '''
                    docker-compose up --build -d
                '''
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
